if(NOT DEFINED EIGEN3_INCLUDE_DIR)
	find_package(Eigen3 REQUIRED)
endif()

if(NOT DEFINED FFTW_INCLUDES OR NOT DEFINED FFTW_LIB)
	find_package(FFTW3)
endif()

if(NOT DEFINED LUA_INCLUDE_DIR OR NOT DEFINED LUA_LIBRARIES)
	find_package(Lua)
endif()

if(NOT DEFINED PNG_PNG_INCLUDE_DIR OR NOT DEFINED PNG_LIBRARY_RELEASE)
	find_package(PNG)
endif()

if(NOT DEFINED ZLIB_LIBRARY_RELEASE)
	find_package(ZLIB)
endif()
	
if(NOT WIN32)
	find_package(Threads)
endif()

if(GUI)
	if(NOT DEFINED FREETYPE_INCLUDE_DIRS OR NOT DEFINED FREETYPE_LIBRARIES)
		find_package(Freetype)
	endif()
	
	if(WIN32)
		if(NOT DEFINED WXWIDGETS_INCLUDES OR NOT DEFINED WXWIDGETS_BASE OR NOT DEFINED WXWIDGETS_CORE OR NOT DEFINED WXWIDGETS_GL OR NOT DEFINED WXWIDGETS_ADV)
			find_path(WXWIDGETS_INCLUDES build.cfg ${wxWidgets_ROOT_DIR}/include)
			find_library(WXWIDGETS_BASE NAMES wxbase PATHS ${wxWidgets_ROOT_DIR}/lib/*)
			find_library(WXWIDGETS_CORE NAMES wxmsw30u_core_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
			find_library(WXWIDGETS_GL NAMES wxmsw30u_gl_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
			find_library(WXWIDGETS_ADV NAMES wxmsw30u_gl_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
			if(MSVC)
				find_library(WXWIDGETS_PNG NAMES wxmsw30u_png_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
				find_library(WXWIDGETS_JPEG NAMES wxmsw30u_jpeg_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
				find_library(WXWIDGETS_TIFF NAMES wxmsw30u_tiff_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
				find_library(WXWIDGETS_ZLIB NAMES wxmsw30u_zlib_gcc_custom PATHS ${wxWidgets_ROOT_DIR}/lib/)
			endif()
		endif()
	else()
		message("Looking for wxWidgets")
		find_package(wxWidgets REQUIRED gl core base adv)
		message("Found wxWidgets " ${wxWidgets_FOUND})
	endif()
endif()